import { network } from "hardhat";
import fs from "fs";
import path from "path";

async function main() {
  console.log("Deploying contracts to local hardhat node...");

  const { viem } = await network.connect();
  const [deployer] = await viem.getWalletClients();
  const publicClient = await viem.getPublicClient();

  console.log("Deployer:", deployer.account.address);

  // 1. Deploy MockALX token
  console.log("\n1. Deploying MockALX...");
  const mockALX = await viem.deployContract("MockALX");
  console.log("MockALX deployed to:", mockALX.address);

  // 2. Deploy ALXStakingPool
  console.log("\n2. Deploying ALXStakingPool...");
  const stakingPool = await viem.deployContract("ALXStakingPool", [
    mockALX.address,
    deployer.account.address,
  ]);
  console.log("ALXStakingPool deployed to:", stakingPool.address);

  // 3. Mint some tokens to deployer for testing
  console.log("\n3. Minting test tokens...");
  const mintAmount = 1000000n * 10n ** 18n; // 1,000,000 ALX
  await mockALX.write.mint([deployer.account.address, mintAmount]);
  console.log("Minted 1,000,000 ALX to deployer");

  // 4. Transfer some tokens to staking pool for rewards
  const poolRewards = 500000n * 10n ** 18n; // 500,000 ALX for rewards
  await mockALX.write.transfer([stakingPool.address, poolRewards]);
  console.log("Transferred 500,000 ALX to staking pool for rewards");

  // 5. Get chain ID
  const chainId = await publicClient.getChainId();

  // 6. Generate .env.local
  const envContent = `# Auto-generated by deploy-local.ts
# Chain Configuration
NEXT_PUBLIC_CHAIN_ID=${chainId}
NEXT_PUBLIC_CHAIN_NAME=Hardhat Local

# Contract Addresses
NEXT_PUBLIC_STAKING_POOL_ADDRESS=${stakingPool.address}
NEXT_PUBLIC_ALX_TOKEN_ADDRESS=${mockALX.address}

# RPC URL
NEXT_PUBLIC_RPC_URL=http://127.0.0.1:8545
`;

  const envPath = path.join(process.cwd(), ".env.local");
  fs.writeFileSync(envPath, envContent);
  console.log("\n4. Generated .env.local");

  console.log("\n========================================");
  console.log("Deployment complete!");
  console.log("========================================");
  console.log("MockALX:", mockALX.address);
  console.log("ALXStakingPool:", stakingPool.address);
  console.log("Chain ID:", chainId);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
